# Generated by Django 4.0.1 on 2022-02-06 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=1000, null=True)),
                ('last_name', models.TextField(blank=True, max_length=1000, null=True)),
                ('gender', models.TextField(blank=True, max_length=1000, null=True)),
                ('email', models.TextField(blank=True, max_length=1000, null=True)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='home/images')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
